# Generated by Django 3.2.3 on 2022-05-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posts_are',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_category', to='post.post'),
        ),
    ]
