# Generated by Django 3.2.3 on 2022-05-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[], default='General', max_length=50),
        ),
    ]
