# Generated by Django 3.2.3 on 2022-05-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='post.post'),
        ),
    ]
