# Generated by Django 4.0.4 on 2022-05-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_country_remove_category_post_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
