version: "3.9"
   
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=heka_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  annoDB:
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=anno_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  django:
    depends_on:
      - db
    build: .
    volumes:
      - .:/code
    command: sh -c "python manage.py test --verbosity=2"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=heka_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - ANNO_POSTGRES_HOST=annoDB
      - ANNO_POSTGRES_NAME=anno_db
      - ANNO_POSTGRES_USER=postgres
      - ANNO_POSTGRES_PASSWORD=1234
      - DEBUG=False

